### ISSUE TITLE
[feature request] 关于类 dependabot 式回复触发操作的一点想法

### ISSUE THREAD

**Issue by abc1763613206** [OI-wiki/linter#2]
不会写 js ，但是 @Ir1d 让我来把想法备忘下。

pr 回复部分的 webhook 在 GitHub 那里属于 issues 分类中的 [commented](https://docs.github.com/en/developers/webhooks-and-events/events/issue-event-types#commented) ，意味着无法像 [review_requested](https://docs.github.com/en/developers/webhooks-and-events/events/issue-event-types#review_requested) 那样拿到 commits .
ref: https://github.com/OI-wiki/linter/blob/master/index.js#L57

我个人的想法是利用 commented 中的 issue_id （参数里没有的话去 URL 那里截断），然后用这个 API 取 head ： https://docs.github.com/en/rest/reference/pulls#get-a-pull-request--code-samples

值得关注的是，这个 API 在塞进去 Issue 的 ID 时会报 404 错误，所以就不需要额外再区分了。

示例：
1. 正常获取 ： https://hoppscotch.io/?method=GET&url=https://api.github.com&path=/repos/oi-wiki/oi-wiki/pulls/3415&contentType=application/json&headers=%5B%7B%22key%22:%22Accept%22,%22value%22:%22application/vnd.github.v3+json%22,%22active%22:true%7D%5D
![image](https://user-images.githubusercontent.com/30773956/129442606-d41d6737-0f12-41b7-b67b-6f8f5aba6905.png)

2. 塞进 Issue 时报 404： https://hoppscotch.io/?method=GET&url=https://api.github.com&path=/repos/oi-wiki/oi-wiki/pulls/3272&contentType=application/json&headers=%5B%7B%22key%22:%22Accept%22,%22value%22:%22application/vnd.github.v3+json%22,%22active%22:true%7D%5D
![image](https://user-images.githubusercontent.com/30773956/129442611-5640e224-3b0a-495e-9c6b-931c2a1874b9.png)

**Comment by Ir1d** [comment]
https://github.com/OI-wiki/OI-wiki/pull/3806#issuecomment-1036994770 实现了hhh
